on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'phpunit.xml.dist'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'phpunit.xml.dist'

name: static analysis

permissions:
  contents: read

jobs:
  psalm:
    uses: yiisoft/actions/.github/workflows/psalm.yml@d441b6617a4db0da0eb1f641cafb238ea459b299
    with:
      extensions: pdo, pdo_pgsql
      os: >-
        ["ubuntu-latest"]
      php: >-
        ["7.4","8.0","8.1"]
