name: static analysis

on:
  pull_request:
    paths: &paths
      - '.github/workflows/static.yml'
      - 'src/**'
      - 'psalm*.xml'
      - 'composer.json'
  push:
    branches: ['master']
    paths: *paths

permissions:
  contents: read

jobs:
  psalm:
    uses: yiisoft/actions/.github/workflows/psalm.yml@master
    with:
      extensions: pdo, pdo_pgsql
      os: >-
        ['ubuntu-latest']
      php: >-
        ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
